* SATIN DOLL

https://rockwell-music.myshopify.com/collections/rockwell-music-store/products/bruce-springsteen-satin-doll-limited-edition-250-copies

Regular price £21.99

BRUCE SPRINGSTEEN - SATIN DOLL (Live On Radio 1973) 

A Limited Edition of just 250 numbered copies on ORANGE Vinyl

Side One:
9TH JANUARY 1973 - BOSTON - WBCN FM 

1 Satin Doll
2 Bishop danced
3 Circus Song
4 Song To Orphans
5 Does This Bus Stop At 82nd Street?  

Side Two:
31ST MAY 1973 - RICHMOND VIRGINIA - WGOE FM

1 Satin Doll
2 Does This Bus Stop At 82nd Street?
3 Circus Song
4 Growin' Up
5 New York City Song
6 You Mean So Much To Me


* A Self Made Man

1. Roulette
2. Take ’em as They Come
3. Cindy
4. Loose Ends
5. Ricky Wants a Man of Her Own

https://musicbrainz.org/release/2b919376-201e-42bb-930d-5d23a2811b32

Release information

Format:
    12" Vinyl
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    5
Works:
    5
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album
Status:
    Bootleg
Language:
    English
Script:
    Latin
Data Quality:
    Normal

Labels

    Vinyl Sounds Records
    [none] 

Release events

    Europe

* American Tune

A1. Santa Ana (New York, NY, 914 Studios (USA) 28-Jun-1973)
A2. Bishop Danced (New York, NY, Max’s Kansas City (USA) 31-Jan-1973)
A3. Zero and the Blind Terry (New York, NY, 914 Studios (USA) 01-Jul-1973)
A4. Seaside Bar Song (New York, NY, 914 Studios (USA) 28-Jun-1973)
B1. Thundercrack (New York, NY, Max’s Kansas City (USA) 31-Jan-1973)
B2. No Money Down (New York, NY, Bottom Line (USA) 13-Jul-1974)
B3. American Tune (San Francisco, CA, the Matrix (USA) 13-Jan-1970)
B4. Cupid (Lincoln Center, NY, Avery Fisher Hall (USA) 04-Oct-1974)

https://musicbrainz.org/release/cc919f19-721d-430b-a6a2-57ad1449d413

Release information

Barcode:
    [none]
Format:
    12" Vinyl
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    8
Works:
    8
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album + Compilation + Live
Packaging:
    Cardboard/Paper Sleeve
Status:
    Bootleg
Language:
    English
Script:
    Latin
Data Quality:
    Normal

Labels

    Good Taste
    1003 

Release events

    Spain
    1986

* At Home

A1. Wild Kisses - 0:00
A2. Tonight - 3:20
A3. Tonight - 6:11
A4. Tonight - 8:37
A5. Tonight - 11:44
A6. Tonight - 15:05
A7. Tonight - 16:02 16:34
B1. The Ties That Bind - 0:00
B2. The Ties That Bind - 3:40 / 3:56
B3. The Ties That Bind - 7:27 / 8:02 / 8:31
B4. Tonight -  / 11:00
B5. Tonight - 11:55 / 12:25
B6. Atlantic City - 13:08

* At the Edge of Darkness

1. The Fast Song (2:59)
2. Candy’s Boy (4:48)
3. Streets of Fire (3:49)
4. Badlands (4:14)
5. The Promise (5:24)
6. Talk to Me (3:58)
7. Gotta Get That Feeling (3:08)
8. Racin’ in the Street (6:17)
9. Bring on the Night (rehearsal) (2:35)

https://musicbrainz.org/release/89796b74-1fcf-4a07-83b6-6486dd46823a

Release information

Barcode:
    [none]
Format:
    CD
Length:
    37:12
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    9
Works:
    9
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album + Compilation
Packaging:
    Jewel Case
Status:
    Bootleg
Language:
    English
Script:
    Latin
Data Quality:
    Normal

Labels

    Musique Sabot

* Another Side of Bruce Springsteen

1. Held Up Without a Gun (1:17)
2. Be True (3:45)
3. Roulette (3:49)
4. The Big Payback (1:59)
5. Pink Cadillac (3:34)
6. Shut Out the Light (3:53)
7. Johnny Bye Bye (1:49)
8. Stand on It (2:30)
9. Janey, Don’t You Lose Heart (3:23)
10. Lucky Man (3:31)
11. Two for the Road (2:01)
12. I Ain’t Got No Home (3:42)
13. Vigilante Man (4:13)
14. Viva Las Vegas (3:10)
15. Chicken Lips and Lizard Hips (1:43)
16. Part Man, Part Monkey (4:31)
17. Thirty Days Out (4:43)
18. Streets of Philadelphia (4:14)
19. Gypsy Woman (3:33)

https://musicbrainz.org/release/ef06f5fa-13f2-45e3-8479-cb55ebfbaa89

Release information

Barcode:
    [none]
Format:
    CD
Length:
    1:01:20
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    19
Works:
    19
ISRCs:
    2 (show)
AcoustIDs:
    85 (show)
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album + Compilation
Packaging:
    Jewel Case
Status:
    Bootleg
Language:
    English
Script:
    Latin
Data Quality:
    Normal

Labels

    Columbus Records
    COL CD 35D56 

* Before the Fame

1. Lady and the Doctor (4:10)
2. Visitation at Fort Horn (7:38)
3. War Nurse (2:06)
4. Prodical Son (6:56)
5. Eloise (1:04)
6. Evacuation of the West (4:28)
7. Jesse (3:04)
8. Arabian Night (5:55)
9. Camilla Horn (1:04)
10. Family Song (5:04)
11. Marie (4:41)
12. Randolph Street (3:44)
13. Jazz Musician (6:09)

https://musicbrainz.org/release/954eb420-1280-41b3-9326-b90fcabf9e68

Release information

Barcode:
    776702500420
Format:
    CD
Length:
    56:03
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    13
Works:
    13
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album + Compilation
Packaging:
    Jewel Case
Status:
    Bootleg
Language:
    English
Script:
    Latin
Data Quality:
    Normal

Labels

    Pony Express Records, Inc.
    PER5895 

Release events

    1996

* Before the Fame

1. Lady and the Doctor (4:10)
2. Southern Son (4:15)
3. War Nurse (2:06)
4. Prodigal Son (6:56)
5. Eloise (1:04)
6. Evacuation of the West (4:28)
7. Jesse (3:04)
8. Border Guard (6:30)
9. Camilla Horn (1:04)
10. Family Song (5:04)
11. Marie (4:41)
12. Randolph Street (3:44)
13. Hollywood Kids (2:38)

https://musicbrainz.org/release/03c69092-da84-4d7a-9d8e-884d1a7554d8


Barcode:
    776702500420
Format:
    CD
Length:
    49:44
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    13
Works:
    13
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album + Compilation
Packaging:
    Jewel Case
Status:
    Official
Language:
    English
Script:
    Latin
Data Quality:
    Normal

Labels

    Pony Express Records, Inc.
    PER5895 

Release events

    United States
    1997

* Before the Fame

1. Lady and the Doctor (4:10)
2. Southern Son (4:15)
3. War Nurse (2:06)
4. Prodigal Son (6:56)
5. Eloise (1:04)
6. Evacuation of the West (4:28)
7. Jesse (3:04)
8. Border Guard (6:30)
9. Camilla Horn (1:04)
10. Family Song (5:04)
11. Marie (4:41)
12. Randolph Street (3:44)
13. Hollywood Kids (2:38)

https://musicbrainz.org/release/483f2bb0-7fad-4bbc-9246-081df98aad1c

Release information

Barcode:
    4530007100145
Format:
    CD
Length:
    49:44
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    13
Works:
    13
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album + Compilation
Packaging:
    Jewel Case
Status:
    Official
Language:
    English
Script:
    Latin
Data Quality:
    Normal

Labels

    Pony Express Records, Inc.
    EKCY 10014 

Release events

    Japan
    1998

* Before the Fame

1. Lady and the Doctor (4:10)
2. Southern Son (4:15)
3. War Nurse (2:06)
4. Prodigal Son (6:56)
5. Eloise (1:04)
6. Evacuation of the West (4:28)
7. Jesse (3:04)
8. Border Guard (6:30)
9. Camilla Horn (1:04)
10. Family Song (5:04)
11. Marie (4:41)
12. Randolph Street (3:44)
13. Hollywood Kids (2:38)

https://musicbrainz.org/release/82530e82-b030-46e0-9c1d-ca70c5fd7833

Release information

Barcode:
    [none]
Format:
    CD
Length:
    49:44
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    13
Works:
    13
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album + Compilation
Packaging:
    Jewel Case
Status:
    Promotion
Language:
    English
Script:
    Latin
Data Quality:
    Normal

Labels

    EPS
    EKCY-10014 (Pred-2) 

Release events

    Japan
    1998

* Before the Fame

1. Lady and the Doctor (4:13)
2. Southern Sun (4:18)
3. War Nurse (2:07)
4. Prodigal Son (6:57)
5. Eloise (1:04)
6. Evacuation of the West (4:28)
7. Jesse (3:04)
8. Border Guard (6:31)
9. Camilla Horn (1:05)
10. Family Song (5:05)

1. Marie (4:46)
2. Randolph Street (3:49)
3. Hollywood Kids (2:43)
4. If I Was the Priest (6:02)
5. Cowboys of the Sea (4:19)
6. Baby Doll (5:09)
7. Two Hearts in True Waltz Time (3:36)
8. Tokyo (4:09)
9. Zero and Blind Terry (version 1) (5:57)
10. Bishop Danced (4:19)

https://musicbrainz.org/release/6a732a34-56a1-422d-86e2-e0a81d7fafb0

Release information

Format:
    2×CD
Length:
    1:23:41
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    20
Works:
    20
AcoustIDs:
    21 (show)
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album + Compilation
Status:
    Bootleg
Language:
    English
Script:
    Latin
Data Quality:
    Normal

Labels

    Pony Express Records, Inc.
    PER5899

* The Best Is Yet to Come

A1. Roulette
A2. Restless Nights
A3. Cindy
A4. Loose Ends
A5. A Man of Her Own
B1. Circus Song
B2. Fire
B3. Raise Your Hand
B4. Point Blank
B5. Hungry Heart

https://musicbrainz.org/release/351b7511-1d36-482d-afa3-b3b7f3150c2e

Release information

Format:
    12" Vinyl
    Show relate/merge tools
    Show Edit rec. buttons
Tracks:
    10
Works:
    10
Tracklist:
    MB, MB+times, EAC

Additional details

Type:
    Album + Compilation + Live
Packaging:
    Cardboard/Paper Sleeve
Status:
    Bootleg
Language:
    English
Script:
    Latin
Data Quality:
    Normal 


* River Refinery

A1	Everybody's looking for somebody - 0:00
A2	I wanna start a whole new life 	 - 0:46
A3	You gotta fight for what you want - 2:12
A4	I don't know - 4:20
A5	Chevrolet deluxe - 5:55
A6	Chevrolet deluxe - 7:12
A7	Chevrolet deluxe - 9:04
A8	Chevrolet deluxe - 10:38
A9	Chevrolet deluxe - 12:23
A10	Chevrolet deluxe - 13:31
A11	The Time in between - 18:12
B1	Whitetown ('79) - 0:00
B2	Mr. Outside - 3:03
        Mr. Outside - 6:10
B3	Held up without a gun - 6:33
B4	You can look (but you better not touch) - 7:38
B5	You can look (but you better not touch) - 8:59
B6	Held up without a gun - 
B7	Point blank - 11:06

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPRR1

* Born to Run

A1 Cynthia - 0:00
A2 None but the Brave - 4:11
A3 (Drop on Down and) Cover Me - 9:37
A4 Sugarland - 14:10
A5 My Love Won't Let You Down #1 - 17:00
B1 Follow That Dream - 0:00
B2 Glory Days - 3:54
B3 Janey, Don't You Loose Heart - 9:09
B4 My Love Won't Let You Down #2 - 13:32
B5 Murder Incorporated - 17:56

* "We Got a Long Night, a Special Night Little Steven Will Come to Play Tonight"

A1 Jungleland - 0:00
A2 Two Hearts - 10:30
A3 Drift Away - 14:00
B1 Born to Run - 0:00
B2 Detroit Medley - 6:22
B3 Twist and Shout - 15:47 ?
B4 Do You Love Me - Twist and Shout - 21:46 ?

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPWGALN1

* Son You May Kiss the Bride

A1	I Wanna Be Where the bands Are - 0:00
A2	Don't do it to me - 3:39
A3	Rendezvous - 6:27
A4	The Iceman - 9:19 ?
A5	Preacher's daughter - 12:30
A6	Breakout - 17:42
B1	Hearts of stone - 0:00
B2	Endless Night - 5:42
B3	City Nights - 9:37
B4	Goin' Back - 12:44
B5	Son You May Kiss the Bride - 18:19

http://www.brucespringsteen.it/DB/detrec.aspx?code=CDSYMKTB1

* "E" Ticket

A1	Rosalita (ein instrumental) - 0:00
A2	Kitty's Back - 7:07
A3	Thunder Road I - 14:20
A4	Sandy (akustik, nein stimm) - 19:02
B1	Walking in the Street - 0:00
B2	She's the one - 4:02
B3	Paradise by the Sea - 10:21
B4	Born to Run - 14:12
B5	Thunder Road II (akustik) - 18:47
B6	Jungle Land - 23:27

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPET2

* Steets on Fire

1/1	Night - 0:00
1/2	Rendezvous - 3:40
1/3	Spirit in the Night - 6:49
1/4	It's My Life - 13:30
2/1	Thunder Road - 0:00
2/2	Mona - 6:04
2/3	She's the One - 13:04 ?
3/1	Something in the Night - 0:00
3/2	Backstreets - 5:14
3/3	10th Avenue Freeze Out - 12:50
4/1	Jungleland - 0:00
4/2	Rosalita - 9:59

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPSOF1

* He's Not an American Dreamer

1/1	For You - 0:00
1/2	Walking in the Street - 7:21
1/3	Song to orphans - 11:25
1/4	The price you pay - 17:20 ?
2/1	E street shuffle - 0:00
2/2	Stolen car - 12:35
2/3	Wings for Wheels - 17:55

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPHSNAAD1

* Restless Nights

1/1	Be true - 0:00
1/2	A man of her own - 3:39
1/3	Cindy - 6:36
1/4	Roulette - 9:03
1/5	Restless nights - 12:57
2/1	Loose ends - 0:00
2/2	Take Them as they come - 4:17
2/3	You can look... (alternate) - 8:54
2/4	Held up without a gun - 10:53
2/5	The Way - 12:10

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPRN2

* Live Rarities

1/1	Ain't too proud to beg - 0:00
1/2	Heartbreak hotel - 3:25 ?
1/3	Chimes of Freedom - 6:30
1/4	Ballad of Easy Rider - 12:28
1/5	Wooly Bully - 16:14 ?
2/1	Barefootin' - 0:00
2/2	Helpless - 7:02
2/3	Dream baby - 
2/4	Vigilante man - 

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPLR1

* Bruce 1971

1/1	I Got My Mojo Working - 0:00
1/2	Living Rock and Roll - 6:55
1/3     Talking About MY Baby - 11:49
2/1	Hootchie Kootchie Man - 0:00
2/2	Don't You Wanna Be an Outlaw ? - 10:51 ?

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPB11

* Still on the Edge

1/1	The Promise - 0:00
1/2	Instrumental - 5:53
1/3	Beware the Night - 9:33
1/4	Racing in the Street - 13:06
2/1	Factory - 0:00
2/2	Streets of Fire - 2:26
2/3	Candy's Room - 6:26
2/4	Sherry Darlin' - 9:33
3/1	Candy's Room - 0:00
3/2	Badlands - 5:12
3/3	Fire - 9:14
3/4	Sad Eyes - 14:32 ?
4/1	Something in the night - 0:00
4/2	Spanish eyes - 4:48
4/3	Sherry darlin' - 11:21
4/4	Candy's Room - 16:32
5/1	Ramrod - 
5/2	Spanish Eyes - 

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPSOTE1

* Murder Inc.

1/1	Murder Inc. - 0:00
1/2	State trooper - 4:15
1/3	My father's house - 8:11
1/4	Man at the top - 14:09
2/1	Trapped - 0:00
2/2	Wooly Bully - 5:01
2/3	Lost in the flood - 8:13
2/4	Ain't too proud to beg - 14:30

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPMI1

* God Save the Boss!

1/1	Send That Boy to Jail - 0:00
1/2	Goin' Back to Georgia - 6:14
1/3	For You - 11:35
1/4	Something in the Night - 19:21
2/1	Action in the Streets - 0:00
2/2	Drive All Night - 5:32
2/3	I don't wanna go home - 16:59
2/4	Johnny bye bye - 20:25

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPGSTB1

* Do I Have to Say His Name? The Jersey Devil Hits Again

1/1	The promise - 0:00
1/2	Candy's Room (slow version) - 5:43
1/3	Spanish eyes - 10:19
1/4	Racing in the street (alt. version) - 16:16
2/1	Because the night - 0:00
2/2	Fire - 3:24
2/3	The fast song - 8:21
2/4	Jersey girl - 11:15
2/5	Southern son - 17:37
2/6	Cowboys of the sea - 21:11

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPDIHTSHN1

* The Boss Was Here

1/1	Summertime Blues - 0:00
1/2	Wild Billy's Circus Story *Spirit in the Night* - 2:46 ?
1/3	Because the night - 9:02 ?
1/4	Good Rockin' Tonight *Ramrod* - 16:15
2/1	The River - 0:00
2/2	Independence Day - 7:15
2/3	Who Stop the Rain - 16:08
3/1	Not Fade Away / Gloria / She's the one - 0:00
3/2	Raise Your Hand - 13:10
3/3	Darkness on the edge of town - 17:28
4/1	Fallin' in Love With You - 0:00
4/2	Born to run - 2:17 ?
4/3	Devil With a Blue Dress / Good Golly Miss Molly / C.C. Rider / Jenny Take a Ride / I Hear a Train - 6:35 ?
4/4	Twist and shout - 17:20 ?

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPTBWH1

* Amnesty 88

1/1	Born in the USA - 0:00
1/2	The promised land - 6:27
1/3	Cover me - 11:38
1/4	Working on the highway - 14:32 ?

2/1	The river - 0:00
2/2	Cadillac ranch - 6:23
2/3	War - 11:48 ?
2/4	My hometown - 14:49

C1 Thunder Road - 0 :00
C2 Because the Night - 5:35
C3 Glory Days - 10:10 ?
C4 Born to Run - 15:52 ?

D1 Raise Your Hand - 0:00
D2 Chimes of Freedom - 6:43
D3 Get Up Stand Up - 12:17

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPA81

* Do You Love Me

1/1	Born in the USA - 0:00
1/2	Prove it all night - 4:54
1/3	Out in the street - 10:37
1/4	Atlantic City - 16:21
2/1	Open all night - 0:00
2/2	Nebraska - 4:33  ? 9:08 ?
2/3	Cover me - 14:05
2/4	Darlington county - 19:31
3/1	Glory days - 0:00
3/2	The promised land - 7:15
3/3	Johnny bye bye - 14:15
3/4	The river - 17:45
4/1	Badlands - 0:00
4/2	Thunder road - 5:39
4/3	Hungry heart - 12:24
4/4	Dancing in the dark - 16:48 ?
5/1	Cadillac ranch - 0:00
5/2	Sherry darling - 5:13 ?
5/3	No surrender - 11:15
5/4	My hometown - 17:09 ?
6/1	Pink cadillac - 0:00
6/2	Fire - 7:10 ?
6/3	Bobby Jean - 10:20
6/4	Backstreets - 14:30 ?
7/1	Rosalita (Come out tonight) - 0:00
7/2	Jungleland - 13:29
8/1	I'm a rocker - 0:00
8/2	Detroit Medley - 3:48 ?
8/3	Twist and shout - 12:47 ?
8/4	Do you love me? - 17:58 ?

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPDYLM1

* You Better Not Touch

1/1	You can look (but you better not touch) - 0:00
1/2	Born in the USA - 2:18
1/3	Seeds - 7:06
1/4	Darlington county - 14:00
1/5	Mansion on the hill - 22:57
2/1	Fire - 0:00
2/2	Dancing in the dark - 6:40
2/3	Glory days - 11:55 ?
2/4	Follow that dream - 17:41
2/5	Hungry heart - 22:35 ?
2/6	Teach your children - ?

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPYBNT1

* Son of America

1/1     Instrumental - 0:00
1/2	Magic kind of loving - 12:15 ?
1/3	My girl - 17:21

2/1     My Girl (cont.) - 0:00
2/2     Blues Improvisation (unknown, sorry!) - 7:45
2/3     ? (unknown title) - 13:14

3/1	It's all over now Baby Blue - 0:00
3/2	Down the road apiece - 11:17
3/3	Sitting on the Top of the World - 17:53

4/1	Goin' back to Georgia - 0:00
4/2	Resurrection - 5:27

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPSOA1

* And the Band Played

1/1	Spirit in the night - 0:00
1/2	The E street shuffle - 6:08
1/3	4th of July, Asbury Park - 14:09
2/1	And the Band Played - 0:00
2/2	Rosalita - 6:45 ?
2/3	Let the four winds blow - 17:08
2/4	I'm ready - ?

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPATBP1

* Shades of a Big Land

1/1     Intro - 0:00
1/2	Does this bus stop at 52nd street? - 2:12 ?
1/3	Wild Billy's circus Song - 7:46 ?
1/4	Growing up - 13:50 ?
1/5	My Song (part of "New York City serenade") - 17:01
2/1	Incident on 57th street - 0:00
2/2	Mountain of love - 9:30
2/3	Born to run - 12:53
2/4	Thunder road - 17:25

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPSOABL1

* Back in L.A.

1/1	Brilliant disguise - 0:00
1/2	Darkness on the edge of town - 5:19
1/3	Mansion on the hill - 9:03
1/4	Reason to believe - 14:26
1/5	Red headed woman - 19:54 ?
2/1	57 channels (and nothin' on) - 0:00
2/2	The wish - 4:20
2/3	Tougher than the rest - ?
2/4	10th avenue freeze-out - ?
2/5	Soul driver - 19:02
2/6	Wild Billy's circus story - 21:44
3/1	State trooper - 0:00
3/2	Nebraska - 3:12
3/3	When the lights go out - 8:43 ?
3/4	Thunder road - 12:19
3/5	My hometown - 18:24
4/1	Real World - 0:00
4/2	Highway 61 revisited - 4:50
4/3	Across the borderline - 8:42
4/4	My father's house - 13:54
4/5	Atlantic City - 21:31

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPBILA1

* Steel Mill

1/1	Funky Broadway *Soul freakout* - 0:00
1/2	Send That Boy to Jail *He's guilty* - 2:16
1/3	Going back to Georgia - 10:14
1/4	Instrumental *Darkness darkness* - 15:42
2/1	The Wind and the Rain - 0:00
3/1	Resurrection - 0:00
3/2	Garden state parkway blues *I got a woman* - 13:02
4/1	Garden state parkway blues - 0:00
4/2	*Mountain child* - 
4/3	*Rhythm* - 

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPSM1

* Fire / For You

A1 Fire - 0:00
A2 For Your - 2:57
B1 Born to Run - 0:00
B2 No Surrender - 5:15
B3 Tenth Avenur Freeze-Out - 9:40

* I'm on Fire

A1 I'm on Fire - 0:00
A2 Johnny Bye Bye - 2:37
B1 Shut out the Light - 0:00
B2 Jersey Girl (live) - 3:50 ?

* Born in the U.S.A.

A1 Born in the U.S.A. (The freedom mix) - 0:00
B1 Born in the U.S.A. (Dub) - 0:00
B2 Born in the U.S.A. (Radio) - 7:35

* xWith a Little Help From My Friends

1/1	Thunder road - 0:00
1/2	Jole Blon - 6:47
1/3	Fire - 10:10
1/4	You mean so much to me - 15:13
1/5	This little girl - 19:10
2/1	Promised land - 0:00
2/2	In the midnight hour - 4:27
2/3	Havin' a Party - 7:21
2/4	Detriot Medley - 18:00 ?

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPWALHFMF1

* Honeymoon Vol.1

1/0     Intor ?
1/1	Born in the USA - 0:00
1/2	Badlands - 7:34
1/3	Out in the street - 12:53 ?
1/4	Johnny 99 - 18:56
1/5	Darkness on the edge of town - 23:55
2/1	Shut out the light - 0:00
2/2	The river - 5:44
2/3	Darlington county - 11:47
2/4	Prove it all night - 17:16 ?
3/1	Glory days - 0:00
3/2	The promised land - 7:50 ?
3/3	My hometown - 13:37
3/4	Thunder road - 21:04 ?
4/1	Atlantic City - 0:00
4/2	Working on the highway - 5:07 ?
4/3	Trapped - 9:13 ?
4/4	Pink cadillac - 14:03
4/5	When I grow up to be a man - 25:20 ?

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPHV11

* Honeymoon Vol.1

1/1	Cover me - 0:00
1/2	Dancing in the dark - 6:38 ? 
1/3	Hungry heart - 12:06 ?
1/4	Cadillac ranch - 16:23
2/1	Racing in the street - 0:00
2/2	Because the night - 11:59
2/3	Bobby Jean - 17:42 ?
3/1	Rosalita (Come out tonight) - 0:00
3/2	Can't help falling in love - 14:29
3/3	Born to run - 18:28 ?
3/4	Ramrod - 23:19 ?
4/1	Sherry darling - 0:00
4/2	Twist and shout - 5:08
4/3	Do you love me? - 13:01 ?

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPHV21

A1	Downbound train - 0:00
B1	I'm on fire - 0:00

* Glory Days

A1 Glory Days - 0:00
B1 Stand on It - 0:00
B2 The River - 2:27

* I'm Goin' Down

A1 I'm Goin' Down - 0:00
B1 Janey, Don't You Loose Heart - 0:00
B2 Held Up Without a Gun - 3:24

* Cover Me

A1 Cover Me (Undercover Mix) - 0:00
B1 Cover Me (Dub Version) - 0:00
B2 Jersey Girl (live) - 4:11

* War / Merry Christmas Baby

A1 War - 0:00
A2 Merry Christmas Baby - 5:13
B1 Incident on 57th Street (live) - 

* Dancing in the Dark

A1 Dancing in the Dark (Blaster Mix) - 0:00
B1 Dancing in the Dark (Radio) - 0:00
B2 Dancing in the Dark (Dub) - 4:40 ?

* Tougher Than the Rest

A1 Tougher Than the Rest - 0:00
A2 Tougher Than the Rest (live version) - 4:41
B1 Be True (live version) - 0:00
B2 Born to Run (live version - acoustic) - 4:53

* My Hometown

A1 My Hometown - 0:00
B1 Santa Claus Is Comin' to Town - 0:00

* Brilliant Disguise

A1 Brilliant Disguise - 0:00
B1 Lucky Man - 0:00
B2 4th of July, Asbury Park (Sandy) - 3:28

* One Step Up

A1 One Step Up - 0:00
B1 Roulette - 0:00

* Tunnel of Love

A1 Tunnel of Love - 0:00
B1 Santa Claus Is Comin' to Town - 0:00
B2 Two for the Roads - 4:31

* Unknown

A1 Run Through This Jungle - 0:00
A2 Prove It All Night - 2:26 ? 
A3 The Ties That Bind - 7:55
A4 10 Avenut Freeze Out - 11:27
A5 Darkness on the Edge of Town - 16:31
A6 Independence Day - 
B1 Factory - 0:00
B2 Who'll Stop the Rain - 1:55 ?
B3 Two Hearts - 5:18
B4 Out In the Street - 8:03
B5 The Price You Pay - 13:30
B6 This Land Is Your Land - 20:03 ?
B7 The River - 26:00 ?

* This Gun's for Hire

1/1	Born in the USA - 0:00
1/2	Out in the street - 5:20 ?
1/3	Spirit in the night - 10:42 ?
1/4	Atlantic City - 18:14 ?
2/1	State trooper - 0:00
2/2	Reason to believe - 4:37
2/3	I'm going down - 9:46
2/4	Darlington county - 15:50
3/1	Glory days - 0:00
3/2	The promised land - 12:48 ?
4/1	Point blank - 0:00
4/2	I fought the law - 8:05 ?
4/3	Badlands - 10:22 ?
4/4	Thunder road - 15:45
5/1	Hungry heart - 0:00
5/2	Dancing in the dark - 4:35 ?
5/3	Cadillac ranch - 10:44 ?
5/4	Candy's room - 16:10 ?
6/1	I'm on fire - 0:00
6/2	Cover me - 3:30
6/3	Growin' up - 10:11
7/1	Bobby Jean - 0:00
7/2	Jersey girl - 4:20 ?
7/3	Rosalita (Come out tonight) - 10:07 ?
8/1	Santa Claus is comin' to town - 0:00
8/2	Jungleland - 6:00 ?
8/3	Born to run - 15:39 ?  (take speech into account)
9/1	Detroit Medley - 0:00
9/2	Twist and shout - 15:56
10/1    [1984 M.T.V. interview with Mark Goodman] - 0:00

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPTGSFH1

* Dancing in the Park

1/1 Born in the USA - 0:00
1/2 Badlands - 5:36
1/3 Out in the street - 10:54 ?
1/4 Johnny 99 - 17:09
2/1 Atlantic City - 0:00
2/2 The river - 5:55 ?
2/3 Working on the highway - 13:31 ?
2/4 Trapped - 17:35
3/1 Prove it all night - 0:00 
3/2 Glory days - 6:44 ?
3/3 The promised land - 15:46
4/1 My hometown - 0:00
4/2 Thunder road - 7:16
4/3 Cover me - 13:49 ?
5/1 Dancing in the dark - 0:00
5/2 Hungry heart - 5:26
5/3 Cadillac ranch - ?
5/4 Downbound train - 16:46
6/1 I'm on fire - 0:00
6/2 Because the night - 5:26 ?
6/3 Rosalita (Come out tonight) - 11:36
7/1 Can't help falling in love - 0:00
7/2 Born to run - 6:10 ?
7/3 Bobby Jean - 
7/4 Ramrod - 15:06 ?
8/1 Sherry darling - 0:00
8/2 Twist and shout - 

http://www.brucespringsteen.it/DB/detrec.aspx?code=LPDIP1



* Odds and Sods

konniekapow Store


Bruce Springsteen Odds and Sods bootleg RARE live unreleased LP EX E Street Band

I have rated my vinyl in accordance with the following standards:

MINT -Record is as it was brand new.  Never been played.
NEAR MINT - This describes vinyl that has been opened and either never played or played very minimally. No scratches or marks on the vinyl.
EXCELLENT - Record has been played but no scratches.  There may be fingerprints or very light marks from handling.
VERY GOOD - Record may have light scratches or marks and fingerprints. Record sound quality is good and does not skip.
GOOD - Record had been played and shows some signs of wear such as scratches and marks.  Still plays pretty well.
POOR - This record has been well played and may be heavily marked.  Sound quality not great and may skip.

I have rated the sleeves in accordance with the following standards:

MINT -Pristine.  As new.  Unopened.  No bent corners, no fading or water damage and 100% complete.
NEAR MINT - This can include both unopened and opened. May have very slight bends on corners, 100% complete, and no fading or water damage.
EXCELLENT: Has been opened, no bent corners but some slight cracking of the cardboard.
VERY GOOD - Has been opened, plastic removed, minor fading, slight bending on corners and glue may have come away at some edges.
GOOD - Bent corners, worn-in impression of album in jacket, faded or water-damaged (slight).
POOR - This covers badly worn circle impression of album, very badly bent corners, writing on jacket or sleeves, water damage, tears, missing extras, etc.

Artist: Bruce Springsteen

Record: Odds and Sods

Label: n/a

Year: 1984

Format: Vinyl, LP, Album

Vinyl Condition: Excellent

Sleeve Condition: Excellent

Track Listing:

Side A

Red Rocks, Denver, Colorado - August 16, 1981 soundcheck before show:

1. Hungry Heart (instrumental)
2. Prove It all Night
3. Good Rockin' Tonight

Partrix, New Brunswick, New Jersey - January 14, 1984 with John Eddie & Front St. Runners:

4. Sweet Darling
5. Boom-Boom-Boom-Boom
6. Proud Mary
7. Twist & Shout/Hang On Sloopy

Side B

Alpine Valley, East Troy, Wisconsin - July 12 1984:

1. Everybody Wants To Be A Man At The Top
2. Bruce tells the story about the creation: Pink Cadillac

Jack Murphy Center, Murfreesboro, Tennessee - December 9, 1984:

3. Detroit Medley: Devil With The Blue Dress; Good Golly Miss Molly; CC Ryder; Jenny, Jenny, Jenny; Travelin' Band; Intro: The E Street Band; Tennessee Dedication; Devil With The Blue Dress (reprise)


Please make payment via Paypal within 3 working days of winning auction.

Should this be a problem then please contact us and we can possibly wait longer.  However, unless we hear from you items will be relisted after 3 working days.

We will accept payment via paypal only.

However, should you wish to collect the item in person then we will accept cash.


All shipping prices are estimates.

Should you have any queries or require an actual price (once item has been won) then we will be happy to provide this.

We do include an amount for packaging, especially in the case of vinyl records which require very careful packaging. 

Costs for postage in the case of vinyl is a bit higher than normal due to past experience in ending up out of pocket.

Please contact us and ask for a total if you have bought more than one item or feel your postage price is higher than it should be.

We will always try to post within 3 working days.

Please note however that we are individuals and not a business so sometimes it might take us a little bit longer.  Should this be the case we would always contact you to let you know.


We will be happy to consider returns within 7 working days provided buyer contacts us in the first instance.

We will then refund as long as items are returned to us FIRST and that items are in the condition in which they were sent.

We will not refund postage and will expect buyer to pay postage to have items returned.

Certain images/photos are the copyrighted property of Clip Art.com and are used with permission under license. 

* The River Tour 2016

Bruce Springsteen & The E Street Band / 

in 2000s, Bruce Springsteen, E Street Band 2017/03/03	76 Views

Bruce Springsteen & The E Street Band / The River Tour 2016 / 13CD Box Set / BF

This Box contains 13 CDs with 170 tracks. It includes all 144 different songs that have been performed on the River Tour 2016. Incl. 20 page booklet with the complete tracklisting and info.  Soundboard

The River Part 1

1 The Ties That Bind
2 Sherry Darling
3 Jackson Cage
4 Two Hearts
5 Independence Day
6 Hungry Heart
7 Out In The Street
8 Crush On You
9 You Can Look But You Better Not Touch
10 I Wanna Marry You
11 The River
12 Point Blank
13 Cadillac Ranch
14 I’m A Rocker

The River Part 2 + More

1 Fade Away
2 Stolen Car
3 Ramrod
4 The Price You Pay
5 Drive All Night
6 Wreck On The Highway
7 Loose Ends
8 Meet Me In The City
9 Roulette
10 I Wanna Be With You
11 From Small Things (Big Things One Day Come)
12 Be True
13 Detroit Medley
14 Rebel Rebel
15 Purple Rain

Born To Run + More

1 Thunder Road
2 Tenth Avenue Freeze Out
3 Night
4 Backstreets
5 Born To Run
6 She’s The One
7 Meetin Across The River
8 Jungleland
9 Shout (with Bob Seger)
10 Spirit In The Night (w/Rickie Lee Jones)
11 Born To Run (with Joe Grushecky)

Born In The USA + More

1 Born In The U.S.A.
2 Cover Me
3 Darlington County
4 Working On The Highway
5 Downbound Train
6 I’m On Fire
7 No Surrender
8 Bobby Jean
9 I’m Going Down
10 Glory Days
11 Dancing In The Dark
12 My Hometown
13 Pink Cadillac
14 Jersey Girl
15 My Love Will Not Let You Down

Darkness On The Edge Of Town + The Promise

1 Badlands
2 Adam Raised A Cain
3 Something In The Night
4 Candy’s Room
5 Racing In The Street
6 The Promised Land
7 Factory
8 Streets Of Fire
9 Prove It All Night
10 Darkness On The Edge Of Town
11 Iceman
12 Rendevouz
13 The Promise
14 Because The Night
15 Fire
16 Save My Love

Greetings From Asbury Park, NJ + The Rising

1 Blinded By The Light
2 Growin’ Up
3 Does The Bus Stop At 82nd Street
4 Lost In The Flood
5 For You
6 Spirit In The Night
7 It’s Hard To be A Saint In The City
8 Lonesome Day
9 Into The Fire
10 Walikn On A Sunny Day
11 Marys Place
12 You Are Missing
13 The Rising
14 My City Of Ruins

The Wild, The Innocent And Magic + More

1 The E Street Shuffle
2 4th Of July, Ashbury Park (Sandy)
3 Kitty’s Back
4 Incident On 57th Street
5 Rosalita (Come Out Tonight)
6 New York City Serenade
7 Radio Nowhere
8 I’ll Work For Your Love
9 Long Walk Home
10 My Lucky Day

Tunnel of Love, Lucky Town + More

1 Tougher Than The Rest
2 Tunnel Of Love
3 Brilliant Disguise
4 Human Touch
5 Roll Of THe Dice
6 Better Days
7 Lucky Town
8 If I Should Fall Behind
9 Living Proof
10 Secret Garden
11 Murder Incorporated
12 The Ghost Of Tom Joad (with Tom Morello)
13 Youngstown

Wrecking Ball + Nebraska

1 We Take Care Of Our Own
2 Shackled And Drawn
3 Jack Of All Trades
4 Death To My Hometown
5 Wrecking Ball
6 Land Of Hope And Dreams
7 American Land
8 Nebraska
9 Atlantic City
10 Mansion On The Hill
11 Johnny 99
12 Reason To Believe

Acoustics + More

1 Mansion On The Hill (Acoustic)
2 Thunder Road (Acoustic)
3 The Ghost Of Tom Joad (Acoustic)
4 Does This Bus Stop At 82nd Street (Acoustic)
5 Long Walk Home (Acoustic)
6 Growin’ Up (Acoustic)
7 For You (Acoustic)
8 I’ll Work For Your Love (Acoustic)
9 This Hard Land (Acoustic)
10 4th Of July Ashbury Park (Sandy) (Acoustic)
11 Take It Easy (Acoustic)
12 New York City Serenade (Acoustic)

Even More Songs Performed With Other Artists + More

1 American Skin (41 Shots) (with Tom Morello)
2 Because The Night (with Bono)
3 Spirit In The Night (with Vini Lopez)
4 Born To Run (with Elliott Murphy)
5 Light Of Day (with John Grushecky)
6 Bobby Jean (with Eddie Vedder)
7 Shout (with Peter Wolf)
8 Death To My Hometown (with Tom Morello)
9 It’s Hard To Be A Saint In The City (with Vini Lopez)
10 Prove It All Night (1978 Intro)
11 Growin’ Up
12 Dancing In The Dark

A Bit Rock’n Roll + More

1 The Fever
2 Trapped
3 Thundercrack
4 Rocking All Over The World
5 Pretty Flamingo
6 Twist And Shout
7 Travelin Band
8 Lucille
9 Jole Blon
10 Summertime Blues
11 Seeds
12 Boom Boom
13 Shout

Last But Not Least

1 Santa Claus Is Coming To Town
2 Who’ll Stop The Rain
3 Dream Baby Dream
4 Back In Your Arms
5 Follow That Dream
6 Streets Of Philadelphia
7 This Hard Land
8 Frankie
9 Non But The Brave
10 You Never Can Tell
11 American Skin (41 Shots)
12 Light Of Day
13 Seven Nights To Rock

BF-18

* Whole Lotta Shaking Dublin

Bruce Springsteen / Whole Lotta Shakin’ Dublin / 2CDR / Project Zip -  PJZ-643A/B
Translated text:
Live At Dublin RDS, Dublin, Ireland May 20th 1993. Soundboard

DISC ONE
01. Downbound Train
02. Because The Night
03. Brilliant Disguise
04. Human Touch
05. The River
06. Who’ll Stop The Rain?
07. Souls Of The Departed
08. Born In The USA
09. Light Of Day
10. Settle For Love (with Joe Ely)
11. Glory Days

DISC TWO
01. Thunder Road
02. Born To Run
03. My Beautiful Reward
04. Great Balls Of Fire (with Jerry Lee Lewis)
05. Whole Lotta Shakin’ Goin’ On (with Jerry Lee Lewis)
06. Working On The Highway
07. Rocking All Over the World
08. Bobby Jean

Live At Dublin RDS, Dublin, Ireland May 20th 1993

* Bruce Springsteen / Born To Run Session / 2CD

in 1970s, Bruce Springsteen, Growin Records 2017/05/17	33 Views

Bruce Springsteen / Born To Run Sessions / 2CD / Growin Records

Translated Text:

Recorded Date May 1974-July 1975, Studio: Record Plant In New York  City 914 Sound Studios In Blauvelt. Digitally Remastered.

Bruce Springsteen is the United States itself. Born in the richest country in the world after the Second World War, the boys enjoyed their richness and confidence, adolescence is a society shaking in the Vietnam War, and after becoming an adult a chaotic society after the cold war, blues Life is closely linked with the history of American contemporary history. For Americans Bruce is a special artist, is not there reason to be around here? Conflict between suffering in the process of boys’ growth, contradiction to society and the reality that must live with it, the typical American public expects to send messages to the world through blues. It is exactly “yesterday’s cry”, it is a cry of that era.

The most exciting highlight of the blues concert will be “Runaway without tomorrow”. Always a representative piece of blues played like a push when the venue overheated the concert prior to the encore, also the title song of the third album of the blues released in 1975. The album “Tomorrow without Runaway” was released on August 25, 1975. This album as if it comprehensively encompasses its overwhelming power and powerfulness of songs, the present and the future of rock ‘n’ roll, runs up the chart in a blink of an eye. Until then, I did not appreciate the sales of the album, but still the first achievement point of Blues who repeatedly led the live performance has been fruited as this “runaway without tomorrow”. This work contains the session sound source of this album “Tomorrow Naked Runaway.”

“Thunder Road of Tears” is the 3 version. In Take 1 the song has already been completed perfectly. A thrilling song composition gradually rising from the intro of the piano which starts quietly. As Blues still singing and singing, it seems that the intention of making this a release version was sparse. Take 2 has saxophone inserted in the intro. Whether it is a trace of trial and error, it will eventually be omitted. Ear I got accustomed to the release version, I got a sense of incongruity, but probably this song was judged to be a simple intro by the piano was better. The acoustic version has a completely different melody, and it is a way to break it out as it is understood by lyrics.

The demo take of “Shout at night” begins with the count of blues. It is as if the blues vocal is floating up, while keeping the performance full of running performance, it seems to be sought for singing and turning. Perhaps they are singing back in front of the recording orchestra. Because it is lyrics like folding tongue quickly, I can not wipe the impression that it is still incomplete. This song also has a double track track of vocals. Here you can see that singing quite politely, so that there is no gap in the vocals.

“Back street” is recorded in this version 4 versions. The blues is already fully open from Take 1. Especially, it turns out that singing with the withered utterance of “Ha ~ Lonzaba ~ ickstreit ♪” intentionally puts other parts and shades. Take 2 starting from the count is a high degree of completeness that it is OK to release as it is. With version with credits with With Strings, the instrument which was eventually cut from the release version was left intact. From the intro guitar solo was inserted, its impression has become quite different. Since the guitar was piled up all the time from the beginning all the time, this was also cut and it was correct.

Recorded at the end of Disc 1 is a song that was recorded while being recorded at the time of recording this album. “Lonely Night In The Park” is rather a song close to the second album. “Linda Let Me Be The One” is a ballad with a beautiful melody. “Walking In The Street” is a song known also as a temporary title “Lovers In The Cold”. The lyrics seem to be incomplete yet, and blues is a part of chasing the melody with Hamming saying “Wowowo”. “A Love So Fine” is a song like Oldies ‘cover which considers the old rock’ n ‘roll of the 50’ s. Unfortunately the lyrics have not been entered yet and only the performance is recorded.

And I kept you waiting “tomorrow without a runaway”. The introduction part with the base on the front, and the impressive riff repeated with glittering performance. The way of making this strong and moderate is making this song masterpieces. It is surprising that a female chorus is included. Whether it was not good to exaggerate anything so far, whether it was overkill or not, at such a judgment it will eventually have been omitted from the release version. In addition, this song also has a double track version of vocals.

“Naruta” is a title like a light love song, while spectacular songs are overflowing with blues taste all the time. It is a masterpiece whose drums are put on the front, emphasize the rhythm, and somewhat echoed vocals are singing very rarely. Although it is recorded two take in this work, both are separate from the release version. Alternate take 2 is a vividness as if blues is singing in front of you in a closed room. This is because it eliminates all effects on vocals and it is a raw song on a single track.

“Meeting · Across the River” was called “Heist” as temporary title during recording. The two takes recorded in this work were all recorded as their working title. It is unique in Blues that the saxophone sound does not feel urban snobbing.

And “Jungle Land” decorating the end of the album. Take 1 starts with a murmuring count of Blues, and suddenly the orchestra has been extensively fascinated. It is an orchestration where there seems to be no whereabouts. Take 2 begins with a clunky count of Blues, again from the voice that I think as stuff somehow. While the song is nearly completed, it is as though singing has not been fixed and trying various singing methods. Take 3 also begins counting, but I am surprised to start with the sound of a string instrument like a suspense drama. Because it was too unfavorable, there is a voice that blues is laughing behind. The last take is a sound source that is rehearsing with concentrating only on the part whether it was not able to decide the ending part of this magnificent song. The woman staff in the studio is doing a suggestion and also shows how it is done. It is surprising that women’s soprano solo is given. Of course it will eventually be cut, but in the process of trial and error it can not be forbidden to be surprised that such an idea without such a fly has been tried.

It is a set of 2 covering the studio / sound source of the famous board “Tomorrow Naki Runaway” engraved in the rock history as the third album by Bruce Springsteen. Permanent preservation of a beautiful picture / disk specification A tightly pressed board.

DISC ONE
THUNDER ROAD
01. take 1
02. take 2
03. take 3
04. acoustic version

NIGHT
05. demo
06. double vocal track

BACKSTREETS
07. take 1
08. take 2
09. with strings #1
10. with strings #2

OUTTAKES
11. Lonely Night In The Park #1
12. Lonely Night In The Park #2
13. Linda Let Me Be The One
14. Walking In The Street a.k.a. Lovers In The Cold
15. A Love So Fine

DISC TWO
BORN TO RUN
01. with strings
02. with strings & double vocal
03. instrumental basic track

SHE’S THE ONE
04. alternate take 1
05. alternate take 2

MEETING ACROSS THE RIVER
06. working title “Heist” take 16
07. working title “Heist”

JUNGLELAND
08. alternate take #1
09. alternate take #2
10. alternate take #3
11. rehearsal for the ending

Growin Records. GW18/19

* Once Upon A Time In The West: Nashville 1981

Live At Municipal Auditorium, Nashville, Tennessee February 26th 1981

DISC 1

Badlands
Tenth Avenue Freeze-Out
Darkness On The Edge Of Town
Independence Day
Who’ll Stop The Rain
Two Hearts
Out In The Street
Thunder Road
This Land Is Your Land
The River
Prove It All Night
The Promised Land
Cadillac Ranch
Sherry Darling

Hungry Heart
Fade Away
Because The Night
You Can Look (But You Better Not Touch)
Stolen Car
Wreck On The Highway
Backstreets
Ramrod
Rosalita (Come Out Tonight)

I’m A Rocker
Jungleland
Born To Run
Detroit Medley / High School Confidential / I’m Ready

* Boston 1977: Legend From The Music Hall Boston

Bruce Springsteen & The E Street Band / Boston 1977 Legend From The Music Hall Boston / 6CD

in 1970s, Bruce Springsteen, E Street Band, Non Label 2013/01/09	113 Views

Bruce Springsteen & The E Street Band / Boston 1977 Legend From The Music Hall Boston / 6CD / Non Label

Translated Text:

Live at Boston Music Hall, Boston, MA. USA 22nd, 23rd & 24th March 1977

Disc 1(73:12)

Intro
Night
Don’t Look Back
Spirit In The Night
It’s My Life
Thunder Road
Mona / She’s The One
Tenth Avenue Freeze-out
Action In The Streets
Backstreets

Disc 2(55:33)

Jungleland
Rosalita
Born To Run
The Promise
Quarter to Three
You Can’t Sit Down

Live at Boston Music Hall, Boston, MA. USA 23rd March 1977

Disc 3(60:11)

Intro
Night
Don’t Look Back
Spirit In The Night
Incident On 57th Street
Thunder Road
Mona / She’s the One
Tenth Avenue Freeze-out
Growin’ Up

Disc 4(70:24)

Backstreets
Jungleland
Rosalita
Born To Run
Quarter To Three
Little Latin Lupe Lu
You Can’t Sit Down

Live at Boston Music Hall, Boston, MA. USA 24th March 1977

Disc 5(69:31)

Intro
Night
Don’t Look Back
Spirit In The Night
Incident On 57th Street
Thunder Road
Mona / She’s The One
Tenth Avenue Freeze-out
Growin’ Up
It’s Hard To Be A Saint In The City

Disc 6(79:59)

Backstreets
Jungleland
Rosalita
Born To Run
Quarter To Three
Little Latin Lupe Lu
You Can’t Sit Down
(Your Love Keeps Lifting Me) Higher And Higher

Bruce Springsteen – Lead and Backing Vocals, Guitar, Harmonica, Piano
Roy Bittan – Piano, Keyboards, Backing Vocals
Clarence Clemons – Tenor, Baritone and Soprano Saxophones, Backing Vocals, Percussion
Danny Federici – Organ, Piano, Accordion, Glockenspiel, Backing Vocals
Garry Tallent – Bass, Backing Vocals, Percussion
Steven Van Zandt – Guitar, Mandolin, Backing Vocals Max Weinberg – Drums
John Binkley – Trumpet Ed De Palma – Saxophone Dennis Orlock – Trombone Steve Paraczky – Trumpet

* Boston 1977: Are You Ready For The Final Moment?

Bruce Springsteen & The E Street Band / Boston 1977 Are You Ready For The Final Moment / 3CD

in 1970s, Bruce Springsteen, Non Label 2012/12/11	111 Views

Bruce Springsteen & The E Street Band / Boston 1977 Are You Ready For The Final Moment / 3CD /Non Label

Translated Text:

Live at Boston Music Hall, Boston, MA. USA 25th March 1977

Disc 1(67:50)

Intro
Night
Don’t Look Back
Spirit In The Night
Incident On 57th Street
Thunder Road
Mona / She’s The One
Tenth Avenue Freeze-Out
Action In The Streets
It’s Hard to Be A Saint In The City

Disc 2(51:34)

Backstreets
Jungleland
Rosalita (Come Out Tonight)
Born To Run

Disc 3(39:34)

Audience
Quarter to Three
Little Latin Lupe Lu
You Can’t Sit Down
(Your Love Keeps Lifting Me) Higher And Higher

* 

1.  New York City Serenade    13:24
2.  Night    03:14
3.  It's Hard To Be A Saint In The City    04:53
4.  Cover Me    04:47
5.  Radio Nowhere    04:11
6.  Glory Days    06:08
7.  Hungry Heart    06:05
8.  The River    06:25
9.  Youngstown    05:52
10.  Murder Incorporated    06:17
11.  Johnny 99    07:16
12.  Ramrod    06:00
13.  You Can Look (But You Better Not Touch)    03:26
14.  Death To My Hometown    05:02
15.  Drive All Night    10:34
16.  I'm Goin' Down    04:23
17.  Because the Night    06:01
18.  The Rising    05:01
19.  Badlands    06:15
20.  Land of Hope and Dreams    08:42
21.  Backstreets    08:10
22.  Born to Run    05:26
23.  Seven Nights to Rock    03:42
24.  Dancing in the Dark    07:27
25.  Tenth Avenue Freeze-Out    05:39
26.  Shout    07:16
27.  Bobby Jean    05:08

* 

1.  New York City Serenade    13:30
2.  American Land    04:38
3.  The Ties That Bind    03:43
4.  No Surrender    05:10
5.  Land of Hope and Dreams    07:47
6.  Trapped    05:15
7.  Spirit In The Night    09:01
8.  Glory Days    05:47
9.  Hungry Heart    05:45
10.  Wrecking Ball    06:19
11.  Youngstown    06:18
12.  Something in the Night    04:47
13.  Darlington County    10:38
14.  Brown Eyed Girl    04:29
15.  Murder Incorporated    06:10
16.  Death To My Hometown    03:51
17.  Racing in the Street    09:51
18.  Because the Night    06:05
19.  She's the One    05:18
20.  The Rising    05:12
21.  Badlands    06:15
22.  Thunder Road    08:20
23.  If I Should Fall Behind    03:47
24.  Born to Run    05:24
25.  Dancing in the Dark    09:03
26.  Tenth Avenue Freeze-Out    05:54
27.  Shout    09:22
28.  Rosalita (Come Out Tonight)    09:29

* 

1.  Don't Hang Up    02:13
2.  American Land    04:37
3.  The Ties That Bind    03:44
4.  No Surrender    05:00
5.  Two Hearts    03:58
6.  The Promised Land    05:46
7.  Glory Days    05:44
8.  Hungry Heart    05:25
9.  Wrecking Ball    06:42
10.  New York City Serenade    11:16
11.  Atlantic City    06:30
12.  Johnny 99    07:04
13.  Murder Incorporated    06:19
14.  Death To My Hometown    04:33
15.  The River    06:51
16.  Mary's Place    09:10
17.  Darlington County    06:24
18.  Working On The Highway    04:45
19.  I'm On Fire    03:41
20.  Because the Night    05:43
21.  The Rising    05:01
22.  Badlands    06:22
23.  Land of Hope and Dreams    10:15
24.  Long Walk Home    03:29
25.  Born to Run    05:30
26.  Dancing in the Dark    07:25
27.  Tenth Avenue Freeze-Out    05:06
28.  Shout    08:22
29.  Twist and Shout    04:37

* 

1.  American Land    05:12
2.  Lonesome Day    04:18
3.  My Love Will Not Let You Down    05:37
4.  Out in the Street    07:18
5.  Sherry Darling    04:59
6.  Hungry Heart    05:32
7.  Glory Days    06:11
8.  This Hard Land    06:30
9.  New York City Serenade    11:44
10.  Prove It All Night    08:43
11.  Trapped    05:12
12.  Youngstown    06:08
13.  Cover Me    04:20
14.  Death To My Hometown    04:12
15.  My City of Ruins    09:24
16.  Cadillac Ranch    05:51
17.  I'm Goin' Down    05:20
18.  Waitin' on a Sunny Day    06:18
19.  Because the Night    05:16
20.  Badlands    06:12
21.  Thunder Road    08:41
22.  Born to Run    05:29
23.  Seven Nights to Rock    03:36
24.  Dancing in the Dark    07:13
25.  Tenth Avenue Freeze-Out    05:13
26.  Shout    09:23
27.  Twist and Shout    05:53

* 


1.  New York City Serenade    12:36
2.  American Land    04:34
3.  The Ties That Bind    03:42
4.  No Surrender    05:03
5.  Out in the Street    06:41
6.  My Love Will Not Let You Down    06:04
7.  Hungry Heart    06:57
8.  Long Tall Sally    03:13
9.  Wrecking Ball    06:16
10.  Darkness On The Edge Of Town    04:58
11.  American Skin (41 Shots)    08:56
12.  Youngstown    06:03
13.  The Promised Land    05:59
14.  Mary's Place    09:48
15.  Candy's Room    03:11
16.  She's the One    05:26
17.  Downbound Train    04:32
18.  I'm On Fire    03:53
19.  Because the Night    05:28
20.  The Rising    05:07
21.  Badlands    06:20
22.  Thunder Road    08:03
23.  Jungleland    11:18
24.  Born to Run    05:21
25.  Dancing in the Dark    07:02
26.  Tenth Avenue Freeze-Out    06:00
27.  Shout    08:36
28.  Bobby Jean    05:26

* 

1.  The Promised Land    05:06
2.  American Land    04:34
3.  Badlands    06:05
4.  Out in the Street    06:21
5.  Two Hearts    05:14
6.  Growin' Up    06:48
7.  Blinded by the Light    05:53
8.  Spirit In The Night    10:09
9.  I'm Goin' Down    04:00
10.  Hungry Heart    05:54
11.  Wrecking Ball    06:26
12.  The River    06:24
13.  Youngstown    06:02
14.  Johnny 99    06:42
15.  Working On The Highway    05:04
16.  Glory Days    06:02
17.  Because the Night    06:04
18.  The Rising    05:06
19.  Rosalita (Come Out Tonight)    09:32
20.  Jungleland    11:50
21.  Born to Run    05:36
22.  Dancing in the Dark    08:28
23.  Tenth Avenue Freeze-Out    05:25
24.  Shout    08:06
25.  Bobby Jean    05:53
26.  Thunder Road    05:54

* 

1.  New York City Serenade    13:54
2.  Lucky Town    05:33
3.  Janey Don't You Lose Heart    03:53
4.  Rendezvous    03:15
5.  Be True    05:48
6.  Back In Your Arms    16:25
7.  Better Days    04:34
8.  The Ties That Bind    03:40
9.  Out in the Street    06:16
10.  Hungry Heart    06:19
11.  Wrecking Ball    06:28
12.  Leap Of Faith    04:16
13.  The River    06:59
14.  Youngstown    06:16
15.  Candy's Room    02:56
16.  She's the One    05:02
17.  Because the Night    06:03
18.  The Rising    04:54
19.  Badlands    06:21
20.  Rosalita (Come Out Tonight)    09:45
21.  Secret Garden    05:18
22.  Born to Run    05:26
23.  Dancing in the Dark    07:30
24.  Tenth Avenue Freeze-Out    05:55
25.  Shout    09:01
26.  Bobby Jean    05:17

* 

1.  New York City Serenade    13:51
2.  Working On A Dream    04:07
3.  Roll of the Dice    06:06
4.  Jole Blon    04:21
5.  Long Time Comin'    05:32
6.  Growin' Up    06:00
7.  Out in the Street    06:28
8.  No Surrender    04:59
9.  Hungry Heart    06:35
10.  Mary's Place    08:34
11.  Fire    03:20
12.  Follow That Dream    04:08
13.  The River    07:04
14.  American Skin (41 Shots)    08:53
15.  The Promised Land    05:47
16.  Downbound Train    04:15
17.  I'm On Fire    03:35
18.  Because the Night    05:40
19.  She's the One    05:21
20.  Badlands    05:35
21.  Rosalita (Come Out Tonight)    10:44
22.  Jungleland    11:04
23.  Born to Run    05:47
24.  Dancing in the Dark    08:22
25.  Tenth Avenue Freeze-Out    05:40
26.  Shout    09:15
27.  Thunder Road    06:46

* 

1.  Who'll Stop The Rain?    03:31
2.  Badlands    06:05
3.  Out in the Street    07:29
4.  I Fought The Law    02:09
5.  Jole Blon    05:38
6.  Waitin' on a Sunny Day    06:52
7.  I'm Goin' Down    03:34
8.  Hungry Heart    05:48
9.  Mary's Place    09:26
10.  None But The Brave    05:40
11.  Wrecking Ball    06:10
12.  You Can Look (But You Better Not Touch)    03:21
13.  Death To My Hometown    04:26
14.  The River    06:57
15.  Youngstown    06:19
16.  The Promised Land    05:44
17.  Working On The Highway    05:10
18.  Glory Days    06:33
19.  Darlington County    07:18
20.  Because the Night    05:48
21.  The Rising    05:17
22.  Rosalita (Come Out Tonight)    11:20
23.  No Surrender    05:12
24.  Born to Run    05:36
25.  Dancing in the Dark    08:41
26.  Tenth Avenue Freeze-Out    05:51
27.  Shout    09:51
28.  Bobby Jean    06:07
29.  Thunder Road    06:20

* 

1.  No Surrender    06:42
2.  Sherry Darling    05:38
3.  It's Hard To Be A Saint In The City    05:13
4.  Jole Blon    03:56
5.  Out in the Street    06:18
6.  Spirit In The Night    09:09
7.  Hungry Heart    05:25
8.  My City of Ruins    12:12
9.  Mary's Place    08:58
10.  Radio Nowhere    04:01
11.  Prove It All Night    05:35
12.  Darkness On The Edge Of Town    05:03
13.  The River    07:11
14.  Youngstown    06:05
15.  The Promised Land    05:41
16.  Working On The Highway    06:38
17.  Glory Days    07:30
18.  Because the Night    05:48
19.  The Rising    05:00
20.  Badlands    06:15
21.  Rosalita (Come Out Tonight)    10:33
22.  My Hometown    05:32
23.  Born to Run    05:33
24.  Dancing in the Dark    08:51
25.  Tenth Avenue Freeze-Out    05:39
26.  Shout    08:37
27.  Bobby Jean    05:48
28.  Thunder Road    06:10

* 

1.  Darlington County    07:16
2.  Working On The Highway    05:07
3.  Glory Days    06:40
4.  Johnny 99    06:59
5.  Prove It All Night    05:31
6.  My Love Will Not Let You Down    05:42
7.  Out in the Street    06:24
8.  Hungry Heart    06:04
9.  My City of Ruins    10:31
10.  Wrecking Ball    06:47
11.  The River    06:45
12.  Youngstown    06:14
13.  American Skin (41 Shots)    08:44
14.  The Promised Land    05:47
15.  Candy's Room    03:12
16.  Because the Night    05:40
17.  The Rising    04:55
18.  Badlands    06:01
19.  Rosalita (Come Out Tonight)    11:03
20.  Backstreets    08:33
21.  Born to Run    05:40
22.  Dancing in the Dark    07:47
23.  Tenth Avenue Freeze-Out    05:34
24.  Shout    09:05
25.  Bobby Jean    05:48
26.  Thunder Road    06:19

* 

* 

1. The End of the Road
2. Seeds
3. One Perfect Moment
4. (I Can’t Get No) Satisfaction
5. I’m Gonna Love You and You’re Gonna Love Me
6. Any Way You Want It
7. Heart Full of the Blues
8. Savin‘ Up
9. You Got Me Shakin‘
10. Drivin‘ in the Rain
11. Give My Love to Rose
12. To You From John
13. For John

* 

Clampdown
Badlands
High Hopes
No Surrender
[Bruce talk]
I Wanna Marry You
Linda Let Me Be the One
Boom Boom
[Bruce talk]
Hearts of Stone
Talk to Me
Wrecking Ball
Hungry Heart
Save My Love
[Bruce talk]
The River
Prove It All Night
My Love Will Not Let You Down
Darlington County
Shackled and Drawn
The Ghost of Tom Joad
The Rising
Land of Hope and Dreams
[encore break]
Highway to Hell
Born to Run
Dancing in the Dark
Tenth Avenue Freeze-Out
Shout
[Bruce talk]
The Wall
Thunder Road

* 

* 


1.  Rockin' All Over The World    04:43
2.  Night    03:19
3.  Out in the Street    06:26
4.  Loose Ends    04:35
5.  Prove It All Night    08:35
6.  We Take Care Of Our Own    04:32
7.  Wrecking Ball    07:43
8.  Death To My Hometown    04:51
9.  My City of Ruins    18:26
10.  Does This Bus Stop at 82nd Street?    06:22
11.  Be True    04:34
12.  Jack Of All Trades    06:46
13.  Downbound Train    05:07
14.  Because the Night    06:00
15.  Lonesome Day    04:33
16.  Darlington County    07:48
17.  Light Of Day - Land Of 1000 Dances    08:20
18.  Shackled And Drawn    08:53
19.  Waitin' on a Sunny Day    10:37
20.  Back In Your Arms    11:39
21.  The Rising    05:11
22.  Badlands    06:27
23.  Land of Hope and Dreams    14:16
24.  We Are Alive    06:49
25.  Born in the U.S.A.    05:20
26.  Born to Run    06:22
27.  Detroit Medley    04:59
28.  Glory Days    05:36
29.  Dancing in the Dark    09:39
30.  Tenth Avenue Freeze-Out    11:35
31.  I Don't Want To Go Home    05:27
32.  (Your Love Keeps Lifting Me) Higher and Higher    07:44
33.  Twist and Shout    12:25


* A Gentleman Of Verona

https://springsteendvds.wordpress.com/2015/09/11/a-gentleman-of-verona-11-apr-1993/

DATE: 11-Apr-1993

LOCATION: Verona

AUDIO: Soundboard

VIDEO: Pro-shot

CHAPTERS: Songs

MENU: Authored

SUBTITLES: No

DVDs: 2

FORMAT: PAL



DVD 1

I’M ON FIRE
BECAUSE THE NIGHT
PROVE IT ALL NIGHT
HUMAN TOUCH
THE RIVER
WHO’LL STOP THE RAIN?
SOULS OF THE DEPARTED
BORN IN THE U.S.A.
LIGHT OF DAY

DVD 2

HUNGRY HEART
GLORY DAYS
THUNDER ROAD
BORN TO RUN
MY BEAUTIFUL REWARD
ROCKIN’ ALL OVER THE WORLD
WORKING ON THE HIGHWAY
BORN TO BE WILD (with Rick “Chainsaw” Lapointe)


BONUS

OSLO – 01-JUN-1993
BORN TO BE WILD (with Rick “Chainsaw” Lapointe)

* 

A1 	Born In The Usa 	
A2 	Badlands 	
A3 	Out In The Street 	
A4 	Johnny 99 	
A5 	Atlantic City 	
B1 	Shout Out The Light 	
B2 	The River 	
B3 	Working On The Highway 	
B4 	Trapped 	
B5 	Darlington County 	

C1 	Glory Days 	
C2 	Promised Land 	
C3 	My Hometown 	
C4 	Thunder Road 	
D1 	Cover Me 	
D2 	Dancing In The Dark 	
D3 	Hungry Heart 	
D4 	Cadillac Ranch 	

E1 	Downbound Train 	
E2 	I'm On Fire 	
E3 	Because The Night 	
F1 	Rosalita 	
F2 	I Can't Help Falling In Love 	

G1 	Born To Run 	
G2 	Bobby Jean 	
G3 	Ramroad 	
H1 	Twist And Shout/Do You Love me 	
H2 	Rolling All Over The World

* 

1. Glory Days (?:??)
2. Youngstown (?:??)
3. Angel Eyes (?:??)
4. Lucky Town (?:??)
5. Streets Of Philadelphia (?:??)
6. Murder Inc (?:??)
7. The Ghost Of Tom Joad (?:??)
8. 57 Channels (?:??)
9. Living Proof (?:??)
10. Dead Man Walkin' (?:??)
11. Shake, Rattle And Roll (?:??)
12. She's The One (?:??)
13. Bo Diddley (?:??)
14. Darkness On The Edge Of Town (?:??)

15. Mountain Of Love (?:??)
16. Born To Run (?:??)
17. E St. Shuffle (?:??)
18. Thunder Road (?:??)
19. She's The One (?:??)
20. 4th Of July, Asbury Park(Sandy) (?:??)
21. Back In The USA (?:??)
22. Jungeland (?:??)
23. Spirit In The Night (?:??)


* 

1. It’s Hard to Be a Saint in the City (?:??)
2. The E-Street Shuffle (?:??)
3. Fire (?:??)
4. Candy’s Room (?:??)
5. Because the Night (?:??)
6. Point Blank (?:??)
7. Thunder Road (?:??)
8. Jungleland (?:??)
9. Santa Claus Is Coming to Town (?:??)

1. Prove It All Night (?:??)
2. Night (?:??)
3. Out in the Street (?:??)
4. Who’ll Stop the Rain (?:??)
5. Glory Days (?:??)
6. Man at the Top (?:??)
7. Dancing in the Dark (?:??)
8. Hungry Heart (?:??)
9. Stolen Car (?:??)
10. Born to Run (?:??)
11. Two Hearts (?:??)
12. Ramrod (?:??)
13. Stand on It (?:??)
14. Janey Don't Lose Your Heart (?:??)

1. Be True (?:??)
2. Spare Parts (?:??)
3. War (?:??)
4. Born in the USA (?:??)
5. Chimes of Freedom (?:??)
6. Paradise by the “C” (?:??)
7. Who Do You Love / She’s the One (?:??)
8. You Can Look (but You Better Not Touch) (?:??)
9. I'm a Coward (?:??)

1. [intro] (?:??)
2. Follow That Dream (?:??)
3. Bobby Jean (?:??)
4. Cadillac Ranch (?:??)
5. Tenth Avenue Freeze-Out (?:??)
6. Sweet Soul Music (?:??)
7. Raise Your Hand (?:??)
8. Twist and Shout (?:??)

* 

Night (?:??)
Spirit in the Night (?:??)
She Is the One (?:??)
Tenth Avenue Freeze Out (?:??)
Rendez-Vous (?:??)
Jungleland (?:??)
Thunder Road (?:??)

* 

The Rising (?:??)
Lonesome Day (?:??)
Ties That Bind (?:??)
Night (?:??)
Empty Sky (?:??)
You’re Missing (?:??)
Waiting on Sunny Day (?:??)
No Surrender (?:??)
World’s Apart (?:??)
Badlands (?:??)
She’s the One (?:??)
Mary’s Place (?:??)

Counting on a Miracle (?:??)
Thunder Road (?:??)
Into the Fire (?:??)
Where the Bands Are (?:??)
Glory Days (?:??)
Born to Run (?:??)
My City of Ruins (?:??)
Born in the U.S.A. (?:??)
Land of Hope and Dreams (?:??)
Dancing in the Dark (?:??)

* 

A1 Thunder Road (7:09)
A2 Tenth Avenue Freeze-Out (3:58)
A3 Spirit In The Night (7:18)
B1 Pretty Flamingo (11:54)
B2 She's The One (5:52)

C1 Born To Run (5:48)
C2 4th Of July, Asbury Park (Sandy) (6:55)
C3 Backstreets (7:11)
D1 Kitty's Back (18:43)

E1 Jungleland (9:21)
E2 Rosalita (Come Out Tonight) (13:12)
F1 Going Back (5:42)
F2 Detroit Medley (7:21)

* 

Point Blank (?:??)
Backstreets (?:??)
Promised Land (?:??)
Because The Night (?:??)
Candy's Room (?:??)
Prove It All Night (?:??)
Fire (?:??)
Independence Day (?:??)
4th Of July, Asbury Park (Sandy) (?:??)
Paradise By The "C" (?:??)
Jungleland (?:??)




* Wachovia Spectrum Philadelphia, PA

1.  The Price You Pay    06:52
2.  Wrecking Ball    06:26
3.  Out in the Street    06:23
4.  Hungry Heart    04:12
5.  Working On A Dream    07:41
6.  Born in the U.S.A.    05:23
7.  Cover Me    04:53
8.  Darlington County    05:56
9.  Working On The Highway    05:11
10.  Downbound Train    04:40
11.  I'm On Fire    03:48
12.  No Surrender    05:01
13.  Bobby Jean    04:22
14.  I'm Goin' Down    04:04
15.  Glory Days    04:21
16.  Dancing in the Dark    07:07
17.  My Hometown    06:59
18.  The Promised Land    06:54
19.  The River    06:51
20.  Long Walk Home    06:53
21.  The Rising    04:53
22.  Born to Run    08:13
23.  (Your Love Keeps Lifting Me) Higher and Higher    10:59
24.  Spirit In The Night    07:22
25.  Loose Ends    04:23
26.  Kitty's Back    14:25
27.  American Land    08:39
28.  Save the Last Dance For Me    03:35
29.  Waitin' on a Sunny Day    06:18
30.  Thunder Road    06:43
31.  Rosalita (Come Out Tonight)    09:33

* 

A1 Opening Comments (4:00)
A2 Tenth Avenue Freeze-Out (4:08)
A3 Spirit in the Night (7:20)
A4 Then She Kissed Me (3:20)
A5 Growin' Up (3:20)
B1 It's Hard to Be a Saint in the City (4:29)
B2 Intro to the E Street Shuffle (10:49)
B3 The E Street Shuffle (10:00)

C1 When You Walk in the Room (3:48)
C2 She's the One (5:03)
C3 Born to Run (4:49)
C4 Thunder Road (5:51)
D1 Intro to Kitty ´ S Back (4:48)
D2 Kitty's Back (19:33)

E1 Rosalita (Come Out Tonight) (11:21)
E2 Encore Comments (1:27)
F1 4th of July, Asbury Park (Sandy) (6:57)
F2 Quarter to Three (6:29)
F3 Closing Comments (4:23)

* 

Opening Comments (?:??)
Tenth Avenue Freeze-Out (?:??)
Spirit in the Night (?:??)
Then She Kissed Me (?:??)
Growin' Up (?:??)
It's Hard to Be a Saint in the City (?:??)
(intro) (?:??)
The E Street Shuffle (?:??)
When You Walk in the Room (?:??)
She's the One (?:??)
Born to Run (?:??)
Thunder Road (?:??)

Intro (?:??)
Kitty's Back (?:??)
Rosalita (Come Out Tonight) (?:??)
Encore Comments (?:??)
4th of July, Asbury Park (Sandy) (?:??)
Quarter to Three (?:??)
Closing Comments (?:??)

Thunder Road (?:??)
Tenth Avenue Freeze-Out (?:??)
Spirit in the Night (?:??)
Pretty Flamingo (?:??)
She's the One (?:??)
Born to Run (?:??)
4th of July, Asbury Park (Sandy) (?:??)
Backstreets (?:??)
Kitty's Back (?:??)

Jungleland (?:??)
Rosalita (Come Out Tonight) (?:??)
Going Back (?:??)
Detroit (medley) (?:??)

* 

Intro
We Take Care Of Our Own
Out In The Street
Wrecking Ball
The Promised Land
Death To My Hometown
Intro: Spirit In The Night
Spirit In The Night

Introducing Born To Run
Thunder Road
Tenth Avenue Freeze Out
Night
Backstreets/Sad Eyes
Born To Run
She's The One
Meeting Across The River
Jungleland
Darlington County
Pay Me My Money Down

Shackled And Drawn
Waitin' On A Sunny Day
The Rising
Badlands
Land Of Hope And Dreams
Mountain Of Love
Born in The U.S.A.
Glory Days
Bobby Jean
Dancing In The Dark
Twist And Shout

* 

Intro
My Love Will Not Let You Down
Leap Of Faith
I'm A Rocker
Better Days
We Take Care Of Our Own
Wrecking Ball
Death To My Hometown
Hungry Heart

Introducing Darkness On The Edge Of Town
Badlands
Adam Raised A Cain
Something In The Night
Candy's Room
Racing In The Street
The Promised Land
Factory
Streets Of Fire
Prove It All Night
Darkness On The Edge Of Town

Intro
Open All Night
Shackled And Drawn
Waitin' On A Sunny Day
Radio Nowhere
The Rising
Thunder Road
Seven Nights To Rock
Born To Run
Dancing In The Dark
Tenth Avenue Freeze Out
American Land

* 

Intro
The Promised Land
Out In The Street
We Take Care Of Our Own
Wrecking Ball
Death To My Hometown
Intro: Spirit In The Night
Spirit In The Night

Introducing Born In The U.S.A.
Born In The U.S.A
Cover Me
Darlington County
Working On The Highway
Downbound Train
I'm On Fire
No Surrender
Bobby Jean
I'm Goin' Down
Glory Days
Dancing In The Dark
My Hometown

Cadillac Ranch
Shackled And Drawn
Waitin' On A Sunny Day
The Rising
Radio Nowhere
Badlands
Thunder Road
Raise Your Hand
Born To Run
Rosalita (Come Out Tonight)
Tenth Avenue Freeze Out
Twist And Shout

* 

* 1980‐11‐05: ASU Activity Center, Arizona State University, Tempe, AZ, USA - https://musicbrainz.org/release/f35b1254-b303-47ad-ba45-a2861563ec8e

https://forums.stevehoffman.tv/threads/bruce-springsteen-missing-songs-from-tempe-dvd-river-box-set-available-for-free.488450/page-3#post-13530975

BORN TO RUN (4.40)
PROVE IT ALL NIGHT (5.52
TENTH AVENUE FREEZE-OUT (4.37)
DARKNESS ON THE EDGE OF TOWN (4.19)
INDEPENDENCE DAY (7.06)
FACTORY (3.12)
JACKSON CAGE (3.27)
TWO HEARTS (2.37)
THE PROMISED LAND (5.43)
OUT IN THE STREET (4.44)
RACING IN THE STREET (8.54)
THE RIVER (6.20)
BADLANDS (5.08)
THUNDER ROAD (5.43)
NO MONEY DOWN (3.10) - CADILLAC RANCH (4.58)
HUNGRY HEART (4.31)
FIRE (5.04)
CANDY’S ROOM (3.11)
SHERRY DARLING (4.36)
HERE SHE COMES (4.35) - I WANNA MARRY YOU (4.29)
THE TIES THAT BIND (3.29)
STOLEN CAR (4.38)
WRECK ON THE HIGHWAY (4.51)
POINT BLANK (7.50)
CRUSH ON YOU (5.01)
RAMROD (4.18)
YOU CAN LOOK (BUT YOU BETTER NOT TOUCH) (3.51)
DRIVE ALL NIGHT (11.27)
BACKSTREETS (7.58)
ROSALITA (COME OUT TONIGHT) (12.46)
I'M A ROCKER (3.27)
JUNGLELAND (9.34)
DETROIT MEDLEY - I HEAR A TRAIN (11.00)

As it stands, the three discs now total 239:32 - not much room for anything else! :)
