* Collection: 1973–2012
** Argentina

https://musicbrainz.org/release/33200d91-8645-4d63-85e7-f6882a24dc7b

text on back cover:

brucespringsteen.net © & ℗ Compilation 2013 Bruce Springsteen / Publicado y
distribuido por Sony Music Entertainment Argentina S.A. Reservados todos los derechos del productor, de los autores
y de los intérpretes de las obras reproducidas en este ejemplar. Prohibida la reproducción, regrabación, alquiler,
préstamo, canje, ejecución pública. Radiodifusión y cualesquiera otro uso no autorizado de estos fonogramas. Sony
Music Entertainment Argentina S.A. Miembro de "CAPIF" y  "AADI/CAPIF".SADAIC/BIEM. Industria Argentina. 8876 545385-2

== Identifiers on Back Cover ==

BRUCESPRINGSTEEN.NET © & ℗ COMPILATION 2013 BRUCE SPRINGSTEEN / PUBLICADO Y
DISTRIBUIDO POR SONY MUSIC ENTERTAINMENT ARGENTINA S.A. RESERVADOS TODOS LOS DERECHOS DEL PRODUCTOR, DE LOS AUTORES
Y DE LOS INTÉRPRETES DE LAS OBRAS REPRODUCIDAS EN ESTE EJEMPLAR. PROHIBIDA LA REPRODUCCIÓN, REGRABACIÓN, ALQUILER,
PRÉSTAMO, CANJE, EJECUCIÓN PÚBLICA. RADIODIFUSIÓN Y CUALESQUIERA OTRO USO NO AUTORIZADO DE ESTOS FONOGRAMAS. SONY
MUSIC ENTERTAINMENT ARGENTINA S.A. MIEMBRO DE "CAPIF" Y "AADI/CAPIF".SADAIC/BIEM. INDUSTRIA ARGENTINA. 8876 545385-2

